_target_: pytorch_lightning.Trainer

gpus: 0

min_epochs: 100
max_epochs: 2000
check_val_every_n_epoch: 50

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
