_target_: src.models.velocity_module.LinearLitModule
lr: 1e-4
alpha: 1
l1_reg: 0.001
kl_reg: 0.1
svgd_reg: 0
temperature: 0.01
n_ens: 100
eval_batch_size: 100
k_hidden: 5
hyper: "linear"
hyper_hidden_dim: [64, 64, 64]
bias: True

# proximal_lambda can also be "adaptive"
# proximal_lambda: 0.1

proximal_lambda: 0.0001
optimizer: "adam"
gamma: 0.999

dims:
  - 12
  - 1

time_invariant: True
