_target_: src.models.parallel_energy_gfn_module.ParallelLinearTrainableCausalGraphGFlowNetModule

env_batch_size: 64
eval_batch_size: 5000
uniform_backwards: False
hidden_dim: 64
embed_dim: 128
lr: 0.001
full_posterior_eval: False
energy_freq: 10
loss_fn: "detailed_balance"
arch: "mlp" # options - ['mlp', 'transformer']
confidence: 0.0
n_steps: 0
bias: true
