_target_: src.models.parallel_energy_gfn_module.PerNodeParallelHyperTrainableCausalGraphGFlowNetModule

env_batch_size: 64
eval_batch_size: 100
full_posterior_eval: False
uniform_backwards: True
debug_use_shd_energy: False
analytic_use_simple_mse_energy: False
loss_fn: "detailed_balance"
alpha: 0
temperature: 0.005
temper_period: 0
prior_lambda: 400 # 10
beta: 0.01
confidence: 0.0
hidden_dim: 128
n_steps: 0 # always set to zero in this version
gfn_freq: 3 # may depend on batch-size
energy_freq: 1 # may depend on batch-size
load_pretrain: True
pretraining_epochs: 0
lr: 1e-5
hyper: "per_node_mlp"
hyper_hidden_dim: [64, 64, 64]
bias: True

dims:
  - 12
  - 1
