# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: lorenz.yaml # choose the datamodule for evaluation
  - model: ngm.yaml
  - callbacks: null
  - logger: csv.yaml
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

test_mode: "default"

# passing checkpoint path is necessary
ckpt_path: null
ckpt: null

# default to old behavior, change working directory to experimental directory
hydra:
  job:
    chdir: True
