_target_: src.datamodules.simulated_datamodule.UnidentifiableSimulatedDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
system: "lorenz"
train_val_test_split: [160, 20, 20]
batch_size: 10
num_workers: 0
pin_memory: False

# lorenz
p: 10
system_kwargs: { "F": 5.0 }

# rossler
#p: 10
#T: 100
#sigma: 0.0

# tumor
#T: 100
#p: 5

# glycolytic
#p: 10 # default p: 7
#T: 100
#sigma: 0.5
#burn_in: 0
#delta_t: 0.001

# cardiovascular
#T: 100
#p: 7 # default p: 4

# Must be integers in range [0, p-(len(vars_to_deidentify) - 1)]
vars_to_deidentify: [0, 1, 0]
