_target_: src.datamodules.simulated_datamodule.UnidentifiableSimulatedVelocityDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
system: "lorenz"
train_val_test_split: [800, 100, 100] #[160, 20, 20]
batch_size: 512
num_workers: 0
pin_memory: False
#system_kwargs: { "F": 5.0 } # for lorenz
p: 10
T: 2
sigma: 0.1
burn_in: 1000
sd: 0.1
delta_t: 0.1

# Must be integers in range [0, p-(len(vars_to_deidentify) - 1)]
vars_to_deidentify: [0, 1, 0]
